In [40]:
import numpy as np

a= np.array([1,2,3,4,5])
print (a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
print(np.zeros(5))
print(np.ones(5))
print(np.arange(0,10,5))
print(np.linspace(0,1,50))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[0 5]
[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


In [12]:
a=np.array([1,2,3])

b=np.array([[1,2,3],[4,5,6]])

print(b.shape)
print(b.ndim)
print(b.size)
print(b.dtype)
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(b.ndim)

(2, 3)
2
6
int64
2


In [ ]:
np.array([1, 2, 3])            # int64   by default
np.array([1.0, 2.0, 3.0])      # float64 by default
np.array([1, 2, 3], dtype=float)  # force float
np.array([1, 2, 3], dtype=str)    # force string

In [ ]:
# Python list — slow, one by one
a = [1, 2, 3, 4]
b = [x * 2 for x in a]   # need a loop

# NumPy array — fast, all at once
a = np.array([1, 2, 3, 4])
b = a * 2                 # [2 4 6 8] ← no loop needed!

#NumPy operates on the entire array at once — this is called vectorization

In [13]:
a = np.array([10, 20, 30, 40])
print(a * 0.5)

[ 5. 10. 15. 20.]


In [15]:
print (np.arange(0,25, 5))
print(np.linspace(0,20,5))

[ 0  5 10 15 20]
[ 0.  5. 10. 15. 20.]


In [25]:
b = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])

print(b[1,2])
print(b[:,2])
print(b[0:2, 0:2])
print(b[b>45]) 
print(b[::-1])

60
[30 60 90]
[[10 20]
 [40 50]]
[50 60 70 80 90]
[[70 80 90]
 [40 50 60]
 [10 20 30]]


In [ ]:
# You're cleaning customer data
customers = np.array([100, 200, 300, 400, 500])

# You want to test something on first 3 only
test = customers[0:3]   # ← VIEW!
test[0] = 0             # ← accidentally wipes original data!

# Safe way
test = customers[0:3].copy()   # ← COPY!
test[0] = 0                    # ← original customers safe 

In [3]:
a= np.array([10,20,30,40,])
b= np.array([1,2,3,4])

print(a+b)
print(a-b)
print(a/b)
print(a**b)

[11 22 33 44]
[ 9 18 27 36]
[10. 10. 10. 10.]
[     10     400   27000 2560000]


In [ ]:
a = np.array([10, 20, 30, 40])

print(a + 5)    # [15 25 35 45]   ← adds 5 to every element
print(a * 2)    # [20 40 60 80]   ← multiplies every element by 2
print(a / 10)   # [1. 2. 3. 4.]
print(a > 25)   # [False False  True  True]  ← you saw this already!

In [ ]:
a = np.array([1, 4, 9, 16, 25])

np.sqrt(a)     # [1. 2. 3. 4. 5.]   ← square root of each
np.log(a)      # [0. 1.38 2.19 2.77 3.21]  ← log of each
np.abs([-1, -2, 3, -4])  # [1 2 3 4]  ← absolute value
np.exp([1, 2, 3])        # [2.71 7.38 20.08]  ← e^x of each

In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])
c = np.array([100, 200])

print(a*3)
print(a+b)
print(np.sqrt(np.array([4, 16, 36, 64])))


sales  = np.array([100, 200, 300, 400])
target = np.array([150, 150, 150, 150])

print( sales > target) 

diff = sales - target
print(diff)           # [-50  50 150 250]   ← how much
print(diff > 0)       # [False True True True]  ← who hit target
print(sales[diff>0])  # [200 300 400]  ← only winners!


[[ 3  6  9]
 [12 15 18]]
[[11 22 33]
 [14 25 36]]
[2. 4. 6. 8.]
[False  True  True  True]


TypeError: 'numpy.ndarray' object is not callable

In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a.shape, a.size, a.ndim)

a = np.array([5, 10, 15, 20, 25, 30])

print(a[1:5:2])
b = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])

print(b[:, -1])

a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[1, 2],
              [3, 4],
              [5, 6]])

# print(a + b)

a = np.array([10, 20, 30, 40, 50])

b = a[1:4]
b[0] = 999

print(a)

a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[1],
              [2]])

print(a * b)

q1. (2,3) 6 2
q2.  [10,20]
q3. [70,80,90]
q4. no , b's shape is need to shrink and strech 
q5. [10,999,30,40,50]
q6.spending[ages>=18]
q7.[[1, 2, 3],[8, 10, 12]]


SyntaxError: unterminated string literal (detected at line 42) (1120315432.py, line 42)

In [19]:
ages     = np.array([15, 25, 35, 17, 45, 16, 55])
spending = np.array([100, 500, 800, 150, 900, 200, 1200])
print(spending[ages>=18])

[ 500  800  900 1200]


In [ ]:
scores = np.array([45, 82, 60, 71, 38, 90, 55, 88])

print(scores[scores>70]) 
print(scores[scores>=60].size)
print(scores[scores<60] +10)


[82 71 90 88]
5
[55 48 65]


Day 2 Reshaping & Stacking

In [31]:
#session 1
#Reshape

a=np.arange(1,13)
print(a)
a.shape

b=a.reshape (6,2)
print(b)
print(b.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
(6, 2)


In [ ]:
# the 1 trick - let numpy figure it out 
print(a.reshape(3,-1))
print(a.reshape(-1,3))

a.reshape(-1,1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [54]:
#Flatten -> copy -> no impact on orginal memory on changes
#ravel() -> view -> will impact

a = np.arange(6)
a
b=a.reshape(3,-1)
b
c= b.flatten()
c[5] = 9
c

r = b.ravel()
r
r[5] =9 
r
b

array([[0, 1],
       [2, 3],
       [4, 9]])