In [1]:
import numpy as np

a= np.array([1,2,3,4,5])
print (a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
print(np.zeros(5))
print(np.ones(5))
print(np.arange(0,10,5))
print(np.linspace(0,1,50))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[0 5]
[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


In [12]:
a=np.array([1,2,3])

b=np.array([[1,2,3],[4,5,6]])

print(b.shape)
print(b.ndim)
print(b.size)
print(b.dtype)
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(b.ndim)

(2, 3)
2
6
int64
2


In [ ]:
np.array([1, 2, 3])            # int64   by default
np.array([1.0, 2.0, 3.0])      # float64 by default
np.array([1, 2, 3], dtype=float)  # force float
np.array([1, 2, 3], dtype=str)    # force string

In [ ]:
# Python list — slow, one by one
a = [1, 2, 3, 4]
b = [x * 2 for x in a]   # need a loop

# NumPy array — fast, all at once
a = np.array([1, 2, 3, 4])
b = a * 2                 # [2 4 6 8] ← no loop needed!

#NumPy operates on the entire array at once — this is called vectorization

In [13]:
a = np.array([10, 20, 30, 40])
print(a * 0.5)

[ 5. 10. 15. 20.]


In [15]:
print (np.arange(0,25, 5))
print(np.linspace(0,20,5))

[ 0  5 10 15 20]
[ 0.  5. 10. 15. 20.]


In [25]:
b = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])

print(b[1,2])
print(b[:,2])
print(b[0:2, 0:2])
print(b[b>45]) 
print(b[::-1])

60
[30 60 90]
[[10 20]
 [40 50]]
[50 60 70 80 90]
[[70 80 90]
 [40 50 60]
 [10 20 30]]


In [ ]:
# You're cleaning customer data
customers = np.array([100, 200, 300, 400, 500])

# You want to test something on first 3 only
test = customers[0:3]   # ← VIEW!
test[0] = 0             # ← accidentally wipes original data! 😱

# Safe way
test = customers[0:3].copy()   # ← COPY!
test[0] = 0                    # ← original customers safe ✅