In [14]:
# Exercise 1:
# Create the following arrays:
# 1. A 1D array of numbers from 0 to 9
# 2. A 2D array of shape (3, 4) filled with zeros
# 3. A 3x3 identity matrix
# 4. A 1D array of 10 equally spaced values between 1 and 100
# 5. A 3x3 array with random integers between 10 and 50
# Print all arrays

# Your code here:
import numpy as np
# 1. A 1D array of numbers from 0 to 9
a = np.array(list(range(10)))
print(f"1D array : {a}" )

# 2. A 2D array of shape (3, 4) filled with zeros
a= np.full((3,4),0)
print(a)

# 3. A 3x3 identity matrix
idm = np.eye(3,3)
print(idm)

# 4. A 1D array of 10 equally spaced values between 1 and 100

linspace_array = np.linspace(1, 100, 10)
print(linspace_array)

# 5. A 3x3 array with random integers between 10 and 50
randint_array = np.random.randint(10, 50, size=(3, 3))
print(randint_array)

1D array : [0 1 2 3 4 5 6 7 8 9]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
[[11 12 17]
 [44 42 27]
 [26 43 46]]


In [20]:
# Exercise 2:
# Create a 3D array with shape (2, 3, 4) using random numbers
# Find and print:
# - Number of dimensions
# - Shape of the array
# - Total number of elements
# - Data type of elements
# - Size in bytes of each element
# - Total memory consumed by the array
# Your code here:

arr = np.random.rand(2, 3, 4)
# print(arr)
# - Number of dimensions
print(f"Number of dimensions : {arr.ndim}")
print(f"Shape of the array: {arr.shape}")
print(f"Total number of elements : {arr.size}")
print("Data type : ", arr.dtype)
print("Bytes per element : ", arr.itemsize)
print("Total memory (bytes) : ", arr.nbytes)


Number of dimensions : 3
Shape of the array: (2, 3, 4)
Total number of elements : 24
Data type :  float64
Bytes per element :  8
Total memory (bytes) :  192


In [31]:
# Exercise 3:
# Create a 1D array of numbers from 1 to 20
# Perform the following operations:
# - Access the first, last, and middle elements
# - Slice the array to get elements from index 5 to 15
# - Get all even numbers using slicing
# - Reverse the array using slicing
# Your code here:
arr = np.array(list(range(1,21)))
print(arr)

print(f"First : {arr[0]}\nLast:{arr[-1]}\nmiddle : {arr[len(arr) // 2]} ")

print(arr[5:15])
print(arr[arr % 2 == 0])
print(arr[::-1])




[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
First : 1
Last:20
middle : 11 
[ 6  7  8  9 10 11 12 13 14 15]
[ 2  4  6  8 10 12 14 16 18 20]
[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [52]:
# Exercise 4:
# Create a 5x5 array with numbers from 1 to 25
# Perform the following tasks:
# - Access the element at row 2, column 3
# - Extract the third row and second column
# - Slice a 3x3 sub-matrix from the center
# - Replace all values in the last row with 0
# - Change the first column to all -1
# Your code here:

arr = np.arange(1, 26).reshape(5, 5)
print(arr.ndim)
print(arr)
print(" Access the element at row 2, column 3 " , arr[1,2])
print("Extract the third row and second column ", arr[2,1])
print("Slice a 3x3 sub-matrix from the center \n",arr[1:4, 1:4])

arr[4, :] = 0
 
arr[:, 0] = -1

print(arr)

2
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
 Access the element at row 2, column 3  8
Extract the third row and second column  12
Slice a 3x3 sub-matrix from the center 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]
[[-1  2  3  4  5]
 [-1  7  8  9 10]
 [-1 12 13 14 15]
 [-1 17 18 19 20]
 [-1  0  0  0  0]]


In [60]:
# Exercise 5:
# Create a 1D array of 15 random integers between 1 and 50
# Perform the following:
# - Select elements at indices [1, 3, 5, 7]
# - Find all elements greater than 25
# - Replace all values less than 10 with 10
# - Count how many values are between 20 and 40 (inclusive)
# - Extract only the odd numbers from the array
# Your code here:

# arr = np.array(list(range(1,51)))
arr = np.random.randint(1,51 ,15)
arr 
print(arr[1],arr[3],arr[5],arr[7] ,arr[[1, 3, 5, 7]] )
print(arr[arr>25])

arr[arr < 10] = 10
print(arr)

print( np.sum((arr >= 20) & (arr <= 40)))

print(arr[arr % 2 != 0])

50 2 42 10 [50  2 42 10]
[50 39 42 36 35 33]
[10 50 10 10 39 42 36 10 22 25 10 35 10 33 15]
6
[39 25 35 33 15]
